#encoding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


countries = Country.create(
  [
    {name:"Ascension Island", abbreviation:"ac"},
    {name:"Andorra", abbreviation:"ad"},
    {name:"United Arab Emirates", abbreviation:"ae"},
    {name:"Afghanistan", abbreviation:"af"},
    {name:"Antigua and Barbuda", abbreviation:"ag"},
    {name:"Anguilla", abbreviation:"ai"},
    {name:"Albania", abbreviation:"al"},
    {name:"Armenia", abbreviation:"am"},
    {name:"Netherlands Antilles", abbreviation:"an"},
    {name:"Angola", abbreviation:"ao"},
    {name:"Antarctica", abbreviation:"aq"},
    {name:"Argentina", abbreviation:"ar"},
    {name:"American Samoa", abbreviation:"as"},
    {name:"Austria", abbreviation:"at"},
    {name:"Australia", abbreviation:"au"},
    {name:"Aruba", abbreviation:"aw"},
    {name:"Åland Islands", abbreviation:"ax"},
    {name:"Azerbaijan", abbreviation:"az"},
    {name:"Bosnia and Herzegovina", abbreviation:"ba"},
    {name:"Barbados", abbreviation:"bb"},
    {name:"Bangladesh", abbreviation:"bd"},
    {name:"Belgium", abbreviation:"be"},
    {name:"Burkina Faso", abbreviation:"bf"},
    {name:"Bulgaria", abbreviation:"bg"},
    {name:"Bahrain", abbreviation:"bh"},
    {name:"Burundi", abbreviation:"bi"},
    {name:"Benin", abbreviation:"bj"},
    {name:"Saint Barthélemy", abbreviation:"bl"},
    {name:"Bermuda", abbreviation:"bm"},
    {name:"Brunei", abbreviation:"bn"},
    {name:"Bolivia", abbreviation:"bo"},
    {name:"British Antarctic Territory", abbreviation:"bq"},
    {name:"Brazil", abbreviation:"br"},
    {name:"Bahamas", abbreviation:"bs"},
    {name:"Bhutan", abbreviation:"bt"},
    {name:"Bouvet Island", abbreviation:"bv"},
    {name:"Botswana", abbreviation:"bw"},
    {name:"Belarus", abbreviation:"by"},
    {name:"Belize", abbreviation:"bz"},
    {name:"Canada", abbreviation:"ca", north_america: true},
    {name:"Cocos [Keeling] Islands", abbreviation:"cc"},
    {name:"Congo - Kinshasa", abbreviation:"cd"},
    {name:"Central African Republic", abbreviation:"cf"},
    {name:"Congo - Brazzaville", abbreviation:"cg"},
    {name:"Switzerland", abbreviation:"ch"},
    {name:"Côte d’Ivoire", abbreviation:"ci"},
    {name:"Cook Islands", abbreviation:"ck"},
    {name:"Chile", abbreviation:"cl"},
    {name:"Cameroon", abbreviation:"cm"},
    {name:"China", abbreviation:"cn"},
    {name:"Colombia", abbreviation:"co"},
    {name:"Clipperton Island", abbreviation:"cp"},
    {name:"Costa Rica", abbreviation:"cr"},
    {name:"Serbia and Montenegro", abbreviation:"cs"},
    {name:"Canton and Enderbury Islands", abbreviation:"ct"},
    {name:"Cuba", abbreviation:"cu"},
    {name:"Cape Verde", abbreviation:"cv"},
    {name:"Christmas Island", abbreviation:"cx"},
    {name:"Cyprus", abbreviation:"cy"},
    {name:"Czech Republic", abbreviation:"cz"},
    {name:"East Germany", abbreviation:"dd"},
    {name:"Germany", abbreviation:"de"},
    {name:"Diego Garcia", abbreviation:"dg"},
    {name:"Djibouti", abbreviation:"dj"},
    {name:"Denmark", abbreviation:"dk"},
    {name:"Dominica", abbreviation:"dm"},
    {name:"Dominican Republic", abbreviation:"do"},
    {name:"Algeria", abbreviation:"dz"},
    {name:"Ceuta and Melilla", abbreviation:"ea"},
    {name:"Ecuador", abbreviation:"ec"},
    {name:"Estonia", abbreviation:"ee"},
    {name:"Egypt", abbreviation:"eg"},
    {name:"Western Sahara", abbreviation:"eh"},
    {name:"Eritrea", abbreviation:"er"},
    {name:"Spain", abbreviation:"es"},
    {name:"Ethiopia", abbreviation:"et"},
    {name:"European Union", abbreviation:"eu"},
    {name:"Finland", abbreviation:"fi"},
    {name:"Fiji", abbreviation:"fj"},
    {name:"Falkland Islands", abbreviation:"fk"},
    {name:"Micronesia", abbreviation:"fm"},
    {name:"Faroe Islands", abbreviation:"fo"},
    {name:"French Southern and Antarctic Territories", abbreviation:"fq"},
    {name:"France", abbreviation:"fr"},
    {name:"Metropolitan France", abbreviation:"fx"},
    {name:"Gabon", abbreviation:"ga"},
    {name:"United Kingdom", abbreviation:"gb"},
    {name:"Grenada", abbreviation:"gd"},
    {name:"Georgia", abbreviation:"ge"},
    {name:"French Guiana", abbreviation:"gf"},
    {name:"Guernsey", abbreviation:"gg"},
    {name:"Ghana", abbreviation:"gh"},
    {name:"Gibraltar", abbreviation:"gi"},
    {name:"Greenland", abbreviation:"gl"},
    {name:"Gambia", abbreviation:"gm"},
    {name:"Guinea", abbreviation:"gn"},
    {name:"Guadeloupe", abbreviation:"gp"},
    {name:"Equatorial Guinea", abbreviation:"gq"},
    {name:"Greece", abbreviation:"gr"},
    {name:"South Georgia and the South Sandwich Islands", abbreviation:"gs"},
    {name:"Guatemala", abbreviation:"gt"},
    {name:"Guam", abbreviation:"gu"},
    {name:"Guinea-Bissau", abbreviation:"gw"},
    {name:"Guyana", abbreviation:"gy"},
    {name:"Hong Kong SAR China", abbreviation:"hk"},
    {name:"Heard Island and McDonald Islands", abbreviation:"hm"},
    {name:"Honduras", abbreviation:"hn"},
    {name:"Croatia", abbreviation:"hr"},
    {name:"Haiti", abbreviation:"ht"},
    {name:"Hungary", abbreviation:"hu"},
    {name:"Canary Islands", abbreviation:"ic"},
    {name:"Indonesia", abbreviation:"id"},
    {name:"Ireland", abbreviation:"ie"},
    {name:"Israel", abbreviation:"il"},
    {name:"Isle of Man", abbreviation:"im"},
    {name:"India", abbreviation:"in"},
    {name:"British Indian Ocean Territory", abbreviation:"io"},
    {name:"Iraq", abbreviation:"iq"},
    {name:"Iran", abbreviation:"ir"},
    {name:"Iceland", abbreviation:"is"},
    {name:"Italy", abbreviation:"it"},
    {name:"Jersey", abbreviation:"je"},
    {name:"Jamaica", abbreviation:"jm"},
    {name:"Jordan", abbreviation:"jo"},
    {name:"Japan", abbreviation:"jp"},
    {name:"Johnston Island", abbreviation:"jt"},
    {name:"Kenya", abbreviation:"ke"},
    {name:"Kyrgyzstan", abbreviation:"kg"},
    {name:"Cambodia", abbreviation:"kh"},
    {name:"Kiribati", abbreviation:"ki"},
    {name:"Comoros", abbreviation:"km"},
    {name:"Saint Kitts and Nevis", abbreviation:"kn"},
    {name:"North Korea", abbreviation:"kp"},
    {name:"South Korea", abbreviation:"kr"},
    {name:"Kuwait", abbreviation:"kw"},
    {name:"Cayman Islands", abbreviation:"ky"},
    {name:"Kazakhstan", abbreviation:"kz"},
    {name:"Laos", abbreviation:"la"},
    {name:"Lebanon", abbreviation:"lb"},
    {name:"Saint Lucia", abbreviation:"lc"},
    {name:"Liechtenstein", abbreviation:"li"},
    {name:"Sri Lanka", abbreviation:"lk"},
    {name:"Liberia", abbreviation:"lr"},
    {name:"Lesotho", abbreviation:"ls"},
    {name:"Lithuania", abbreviation:"lt"},
    {name:"Luxembourg", abbreviation:"lu"},
    {name:"Latvia", abbreviation:"lv"},
    {name:"Libya", abbreviation:"ly"},
    {name:"Morocco", abbreviation:"ma"},
    {name:"Monaco", abbreviation:"mc"},
    {name:"Moldova", abbreviation:"md"},
    {name:"Montenegro", abbreviation:"me"},
    {name:"Saint Martin", abbreviation:"mf"},
    {name:"Madagascar", abbreviation:"mg"},
    {name:"Marshall Islands", abbreviation:"mh"},
    {name:"Midway Islands", abbreviation:"mi"},
    {name:"Macedonia", abbreviation:"mk"},
    {name:"Mali", abbreviation:"ml"},
    {name:"Myanmar [Burma]", abbreviation:"mm"},
    {name:"Mongolia", abbreviation:"mn"},
    {name:"Macau SAR China", abbreviation:"mo"},
    {name:"Northern Mariana Islands", abbreviation:"mp"},
    {name:"Martinique", abbreviation:"mq"},
    {name:"Mauritania", abbreviation:"mr"},
    {name:"Montserrat", abbreviation:"ms"},
    {name:"Malta", abbreviation:"mt"},
    {name:"Mauritius", abbreviation:"mu"},
    {name:"Maldives", abbreviation:"mv"},
    {name:"Malawi", abbreviation:"mw"},
    {name:"Mexico", abbreviation:"mx", north_america: true},
    {name:"Malaysia", abbreviation:"my"},
    {name:"Mozambique", abbreviation:"mz"},
    {name:"Namibia", abbreviation:"na"},
    {name:"New Caledonia", abbreviation:"nc"},
    {name:"Niger", abbreviation:"ne"},
    {name:"Norfolk Island", abbreviation:"nf"},
    {name:"Nigeria", abbreviation:"ng"},
    {name:"Nicaragua", abbreviation:"ni"},
    {name:"Netherlands", abbreviation:"nl"},
    {name:"Norway", abbreviation:"no"},
    {name:"Nepal", abbreviation:"np"},
    {name:"Dronning Maud Land", abbreviation:"nq"},
    {name:"Nauru", abbreviation:"nr"},
    {name:"Neutral Zone", abbreviation:"nt"},
    {name:"Niue", abbreviation:"nu"},
    {name:"New Zealand", abbreviation:"nz"},
    {name:"Oman", abbreviation:"om"},
    {name:"Panama", abbreviation:"pa"},
    {name:"Pacific Islands Trust Territory", abbreviation:"pc"},
    {name:"Peru", abbreviation:"pe"},
    {name:"French Polynesia", abbreviation:"pf"},
    {name:"Papua New Guinea", abbreviation:"pg"},
    {name:"Philippines", abbreviation:"ph"},
    {name:"Pakistan", abbreviation:"pk"},
    {name:"Poland", abbreviation:"pl"},
    {name:"Saint Pierre and Miquelon", abbreviation:"pm"},
    {name:"Pitcairn Islands", abbreviation:"pn"},
    {name:"Puerto Rico", abbreviation:"pr"},
    {name:"Palestinian Territories", abbreviation:"ps"},
    {name:"Portugal", abbreviation:"pt"},
    {name:"U.S. Miscellaneous Pacific Islands", abbreviation:"pu"},
    {name:"Palau", abbreviation:"pw"},
    {name:"Paraguay", abbreviation:"py"},
    {name:"Panama Canal Zone", abbreviation:"pz"},
    {name:"Qatar", abbreviation:"qa"},
    {name:"Outlying Oceania", abbreviation:"qo"},
    {name:"Réunion", abbreviation:"re"},
    {name:"Romania", abbreviation:"ro"},
    {name:"Serbia", abbreviation:"rs"},
    {name:"Russia", abbreviation:"ru"},
    {name:"Rwanda", abbreviation:"rw"},
    {name:"Saudi Arabia", abbreviation:"sa"},
    {name:"Solomon Islands", abbreviation:"sb"},
    {name:"Seychelles", abbreviation:"sc"},
    {name:"Sudan", abbreviation:"sd"},
    {name:"Sweden", abbreviation:"se"},
    {name:"Singapore", abbreviation:"sg"},
    {name:"Saint Helena", abbreviation:"sh"},
    {name:"Slovenia", abbreviation:"si"},
    {name:"Svalbard and Jan Mayen", abbreviation:"sj"},
    {name:"Slovakia", abbreviation:"sk"},
    {name:"Sierra Leone", abbreviation:"sl"},
    {name:"San Marino", abbreviation:"sm"},
    {name:"Senegal", abbreviation:"sn"},
    {name:"Somalia", abbreviation:"so"},
    {name:"Suriname", abbreviation:"sr"},
    {name:"São Tomé and Príncipe", abbreviation:"st"},
    {name:"Union of Soviet Socialist Republics", abbreviation:"su"},
    {name:"El Salvador", abbreviation:"sv"},
    {name:"Syria", abbreviation:"sy"},
    {name:"Swaziland", abbreviation:"sz"},
    {name:"Tristan da Cunha", abbreviation:"ta"},
    {name:"Turks and Caicos Islands", abbreviation:"tc"},
    {name:"Chad", abbreviation:"td"},
    {name:"French Southern Territories", abbreviation:"tf"},
    {name:"Togo", abbreviation:"tg"},
    {name:"Thailand", abbreviation:"th"},
    {name:"Tajikistan", abbreviation:"tj"},
    {name:"Tokelau", abbreviation:"tk"},
    {name:"Timor-Leste", abbreviation:"tl"},
    {name:"Turkmenistan", abbreviation:"tm"},
    {name:"Tunisia", abbreviation:"tn"},
    {name:"Tonga", abbreviation:"to"},
    {name:"Turkey", abbreviation:"tr"},
    {name:"Trinidad and Tobago", abbreviation:"tt"},
    {name:"Tuvalu", abbreviation:"tv"},
    {name:"Taiwan", abbreviation:"tw"},
    {name:"Tanzania", abbreviation:"tz"},
    {name:"Ukraine", abbreviation:"ua"},
    {name:"Uganda", abbreviation:"ug"},
    {name:"U.S. Minor Outlying Islands", abbreviation:"um"},
    {name:"United States", abbreviation:"us", north_america: true},
    {name:"Uruguay", abbreviation:"uy"},
    {name:"Uzbekistan", abbreviation:"uz"},
    {name:"Vatican City", abbreviation:"va"},
    {name:"Saint Vincent and the Grenadines", abbreviation:"vc"},
    {name:"North Vietnam", abbreviation:"vd"},
    {name:"Venezuela", abbreviation:"ve"},
    {name:"British Virgin Islands", abbreviation:"vg"},
    {name:"U.S. Virgin Islands", abbreviation:"vi"},
    {name:"Vietnam", abbreviation:"vn"},
    {name:"Vanuatu", abbreviation:"vu"},
    {name:"Wallis and Futuna", abbreviation:"wf"},
    {name:"Wake Island", abbreviation:"wk"},
    {name:"Samoa", abbreviation:"ws"},
    {name:"People's Democratic Republic of Yemen", abbreviation:"yd"},
    {name:"Yemen", abbreviation:"ye"},
    {name:"Mayotte", abbreviation:"yt"},
    {name:"South Africa", abbreviation:"za"},
    {name:"Zambia", abbreviation:"zm"},
    {name:"Zimbabwe", abbreviation:"zw"},
    {name:"Unknown Region", abbreviation:"zz"}
  ]
)

